<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUejj7ty\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUejj7ty/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUejj7ty.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUejj7ty\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUejj7ty\App_KernelDevDebugContainer([
    'container.build_hash' => 'Uejj7ty',
    'container.build_id' => '455a3634',
    'container.build_time' => 1649178758,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUejj7ty');
