<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJiGhPFU\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJiGhPFU/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJiGhPFU.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJiGhPFU\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJiGhPFU\App_KernelDevDebugContainer([
    'container.build_hash' => 'JiGhPFU',
    'container.build_id' => '93b5fd02',
    'container.build_time' => 1649191664,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJiGhPFU');
