<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerC94UXba\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerC94UXba/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerC94UXba.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerC94UXba\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerC94UXba\App_KernelDevDebugContainer([
    'container.build_hash' => 'C94UXba',
    'container.build_id' => '3e11df9b',
    'container.build_time' => 1649289517,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerC94UXba');
