<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'app_user' => [[], ['_controller' => 'App\\Controller\\UserController::index'], [], [['text', '/user']], [], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'api_login_check' => [[], [], [], [['text', '/api/login_check']], [], [], []],
    'user' => [[], ['_controller' => 'App\\Controller\\UserController::index'], [], [['text', '/api/user']], [], [], []],
    'getOrder' => [['orderCode'], ['_controller' => 'App\\Controller\\OrderController::getOrder'], [], [['variable', '/', '[^/]++', 'orderCode', true], ['text', '/api/getOrder']], [], [], []],
    'getAllOrders' => [[], ['_controller' => 'App\\Controller\\OrderController::getAllOrders'], [], [['text', '/api/getAllOrders']], [], [], []],
    'createOrder' => [[], ['_controller' => 'App\\Controller\\OrderController::createOrder'], [], [['text', '/api/createOrder']], [], [], []],
    'updateOrder' => [['orderCode'], ['_controller' => 'App\\Controller\\OrderController::updateOrder'], [], [['variable', '/', '[^/]++', 'orderCode', true], ['text', '/api/updateOrder']], [], [], []],
    'shippingUpdate' => [['orderCode'], ['_controller' => 'App\\Controller\\OrderController::shippingUpdate'], [], [['variable', '/', '[^/]++', 'orderCode', true], ['text', '/api/shippingUpdate']], [], [], []],
    'deleteOrder' => [['orderCode'], ['_controller' => 'App\\Controller\\OrderController::deleteOrder'], [], [['variable', '/', '[^/]++', 'orderCode', true], ['text', '/api/deleteOrder']], [], [], []],
];
